In [2]:
from cdapython import *
import pandas as pd
from IPython.display import display, Markdown

In [3]:
tables()

['file',
 'mutation',
 'observation',
 'project',
 'subject',
 'treatment',
 'upstream_identifiers']

In [4]:
cda_functions()

You can get complete usage details for each function by calling "help( function_name )".

['tables',
 'columns',
 'column_values',
 'summarize_subjects',
 'summarize_files',
 'get_subject_data',
 'get_file_data',
 'expand_subject_results',
 'expand_file_results',
 'intersect_subject_results',
 'intersect_file_results',
 'release_metadata',
 'get_valid_log_levels',
 'get_log_level',
 'set_log_level',
 'enable_console_logging',
 'disable_console_logging',
 'enable_file_logging',
 'disable_file_logging',
 'get_api_url',
 'set_api_url',
 'cda_functions']

In [5]:
columns(table='project')

,table,column,data_type,nullable,description
0,project,project_id,text,False,A unique identifier for this project minted by...
1,project,project_name,text,False,Full project name.
2,project,project_short_name,text,False,Short project name.
3,project,project_type,text,False,"Project type: one of [ 'collection', 'dbgap_st..."

In [13]:
column_values(column='project_id', filters='*phs*')

                         project_id  value_count
0   dbGaP.study_accession.phs000178            1
1   dbGaP.study_accession.phs000218            1
2   dbGaP.study_accession.phs000235            1
3   dbGaP.study_accession.phs000463            1
4   dbGaP.study_accession.phs000464            1
..                              ...          ...
89  dbGaP.study_accession.phs003163            1
90  dbGaP.study_accession.phs003164            1
91  dbGaP.study_accession.phs003432            1
92  dbGaP.study_accession.phs003488            1
93  dbGaP.study_accession.phs003519            1

[94 rows x 2 columns]

In [15]:
subject_df = get_subject_data(add_columns='project_id')

In [16]:
subject_df.head()

,subject_id,cause_of_death,ethnicity,race,species,year_of_birth,year_of_death,data_source,project_id
0,ALCHEMIST.ALCH-ABBM,<NA>,<NA>,<NA>,human,<NA>,<NA>,[GDC],[GDC.program.d60aaa73-efec-550a-bf5d-b837aa9b5...
1,ALCHEMIST.ALCH-ABC2,<NA>,<NA>,<NA>,human,<NA>,<NA>,[GDC],[GDC.program.d60aaa73-efec-550a-bf5d-b837aa9b5...
2,ALCHEMIST.ALCH-ABD5,<NA>,<NA>,<NA>,human,<NA>,<NA>,[GDC],[GDC.program.d60aaa73-efec-550a-bf5d-b837aa9b5...
3,ALCHEMIST.ALCH-ABE5,<NA>,<NA>,<NA>,human,<NA>,<NA>,[GDC],[GDC.program.d60aaa73-efec-550a-bf5d-b837aa9b5...
4,ALCHEMIST.ALCH-ABE9,<NA>,<NA>,<NA>,human,<NA>,<NA>,[GDC],[GDC.program.d60aaa73-efec-550a-bf5d-b837aa9b5...

In [23]:
subject_df = subject_df[subject_df['project_id'].str.contains('phs')]

In [24]:
subject_df.head()

Empty DataFrame
Columns: [subject_id, cause_of_death, ethnicity, race, species, year_of_birth, year_of_death, data_source, project_id]
Index: []